services:
  subtitler:
    build: .
    ports:
      - "8642:8642"
    # SYS_ADMIN capability needed to mount SMB shares inside the container
    cap_add:
      - SYS_ADMIN
    # Required for CIFS mount
    security_opt:
      - apparmor:unconfined
    env_file: stack.env
